env:
  global:
    - GIT_NAME: deploy-bot
    - GIT_EMAIL: bgcook@lbl.gov
    - GH_REF: git@github.com:brandongc/docs-ci-test.git
language: python
before_script:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=src/ mkdocs build -v --clean
after_success:
  ./travis-deploy.sh
